### PR TITLE
mad token migration from alice deployer

### PR DESCRIPTION
**Pull request by z-j-lin**
## Scope

What is changing with this PR?

## Why?
added task to convert mad token from alicenet deployer to alca 

TODO: execute the following command in the bridge directory
npx hardhat migrate-all-madtoken-to-alca --mad-token-address 0x5B09A0371C1DA44A8E24D36Bf5DEb1141a84d875  --factory-address 0x4b6dF6B299fB6414f45719E0d9e1889269a7843E --alca-address 0xBb556b0eE2CBd89ed95DdEA881477723A3Aa8F8b  --network mainnet --show-stack-traces
the following is a test run

Do you want to convert 12857142.85714285692715008 Madtoken to 19999999.999999999664455679 for 60665 units of gas? (y/n)
y
receipt: {
  to: '0xBb556b0eE2CBd89ed95DdEA881477723A3Aa8F8b',
  from: '0xff55549a3ceEa32FbA4794bf1A649A2363fcda53',
  contractAddress: null,
  transactionIndex: 0,
  gasUsed: BigNumber { value: "50753" },
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004002000000001000000000000000000000000000100000008000000080000000000000000000000000000000000000400020008000000000000000800001200000000000000000010000000000000000000000000000000010000000080000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000008000002000000000000000000000000000000000000000000020000000020000000000000000000000000000000000000000000000000080000000000000000',
  blockHash: '0x980d651d0840fe2f7a5c2d97f339a8074bfea31368f84f32638943fc3c150841',
  transactionHash: '0xaf6bc88dfe2582674c17524b94fa292d7ff84cf3cb20975c3c8c89bd5eeb45cf',
  logs: [
    {
      transactionIndex: 0,
      blockNumber: 17415995,
      transactionHash: '0xaf6bc88dfe2582674c17524b94fa292d7ff84cf3cb20975c3c8c89bd5eeb45cf',
      address: '0x5B09A0371C1DA44A8E24D36Bf5DEb1141a84d875',
      topics: [Array],
      data: '0x0000000000000000000000000000000000000000000aa29b1c62dd13c0000000',
      logIndex: 0,
      blockHash: '0x980d651d0840fe2f7a5c2d97f339a8074bfea31368f84f32638943fc3c150841'
    },
    {
      transactionIndex: 0,
      blockNumber: 17415995,
      transactionHash: '0xaf6bc88dfe2582674c17524b94fa292d7ff84cf3cb20975c3c8c89bd5eeb45cf',
      address: '0xBb556b0eE2CBd89ed95DdEA881477723A3Aa8F8b',
      topics: [Array],
      data: '0x000000000000000000000000000000000000000000108b2a2c2802907fffffff',
      logIndex: 1,
      blockHash: '0x980d651d0840fe2f7a5c2d97f339a8074bfea31368f84f32638943fc3c150841'
    }
  ],
  blockNumber: 17415995,
  confirmations: 1,
  cumulativeGasUsed: BigNumber { value: "50753" },
  effectiveGasPrice: BigNumber { value: "46524785022" },
  status: 1,
  type: 2,
  byzantium: true,
  events: [
    {
      transactionIndex: 0,
      blockNumber: 17415995,
      transactionHash: '0xaf6bc88dfe2582674c17524b94fa292d7ff84cf3cb20975c3c8c89bd5eeb45cf',
      address: '0x5B09A0371C1DA44A8E24D36Bf5DEb1141a84d875',
      topics: [Array],
      data: '0x0000000000000000000000000000000000000000000aa29b1c62dd13c0000000',
      logIndex: 0,
      blockHash: '0x980d651d0840fe2f7a5c2d97f339a8074bfea31368f84f32638943fc3c150841',
      args: [Array],
      decode: [Function (anonymous)],
      event: 'Transfer',
      eventSignature: 'Transfer(address,address,uint256)',
      removeListener: [Function (anonymous)],
      getBlock: [Function (anonymous)],
      getTransaction: [Function (anonymous)],
      getTransactionReceipt: [Function (anonymous)]
    },
    {
      transactionIndex: 0,
      blockNumber: 17415995,
      transactionHash: '0xaf6bc88dfe2582674c17524b94fa292d7ff84cf3cb20975c3c8c89bd5eeb45cf',
      address: '0xBb556b0eE2CBd89ed95DdEA881477723A3Aa8F8b',
      topics: [Array],
      data: '0x000000000000000000000000000000000000000000108b2a2c2802907fffffff',
      logIndex: 1,
      blockHash: '0x980d651d0840fe2f7a5c2d97f339a8074bfea31368f84f32638943fc3c150841',
      args: [Array],
      decode: [Function (anonymous)],
      event: 'Transfer',
      eventSignature: 'Transfer(address,address,uint256)',
      removeListener: [Function (anonymous)],
      getBlock: [Function (anonymous)],
      getTransaction: [Function (anonymous)],
      getTransactionReceipt: [Function (anonymous)]
    }
  ]
}
alca initial mad balance 41458094.804537176608439634
alicenet deployer 0xff55549a3ceEa32FbA4794bf1A649A2363fcda53 initial balance: 12857142.85714285692715008
factory initial balance: 195976299.639196444444444444
factory ending balance: 215976299.639196444108900123
alca initial madtoken balance: 41458094.804537176608439634
alca ending madtoken balance: 54315237.661680033535589714

### CODE REVIEW

**Review by matttyb80 — APPROVED** [review]

**Comment by matttyb80** [comment]
this converts the MAD in the validator lockup to ALCA and transfers the output ALCA to the factory

**Review by iolloyd — COMMENTED** [review]
Do we have supporting tests?

**Comment by Cr0wn-Gh0ul** [comment]
> @iolloyd Do we have supporting tests?
Continuing this question.

@z-j-lin 
- Was the test output you displayed using hardhat forking of mainnet?
- Is there any direct hardhat tests for this?

**Comment by z-j-lin** [comment]
> > @iolloyd Do we have supporting tests?
> > Continuing this question.
> 
> @z-j-lin
> 
> * Was the test output you displayed using hardhat forking of mainnet?
> * Is there any direct hardhat tests for this?

yes

**Review by Cr0wn-Gh0ul — APPROVED** [review]
LGTM

**Pull request merged**
